services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6380:6380'
  web:
      build: .
      container_name: flask-app
      ports:
        - '5000:5000'
      volumes:
        - .:/flask-app
      depends_on:
        - redis

